-- =============================================================================
-- SIMULACIONES - ORDEN SUGERIDO
-- =============================================================================
-- Requisito: base smart_city inicializada con migrate.sql o Docker.
--
-- Objetivo: demostrar los casos de prueba pedidos por la consigna del TP.
-- Estos scripts son AUTO-CONTENIDOS, TRANSACCIONALES y AUTO-VERIFICABLES:
--   - hacen su preparación dentro de BEGIN;
--   - validan resultados con RAISE EXCEPTION;
--   - terminan con ROLLBACK para no ensuciar la base;
--   - si algo falla, psql corta por ON_ERROR_STOP.
--
-- Ejecutar cada archivo por separado:
--   psql -h localhost -p 5433 -U postgres -d smart_city -v ON_ERROR_STOP=1 \
--        -f simulacion/01_caso_basico_asignacion_automatica.sql
--
-- Orden sugerido:
--   01_caso_basico_asignacion_automatica.sql
--   02_caso_basico_cambio_estados.sql
--   03_caso_intermedio_falta_recursos.sql
--   04_caso_intermedio_incidentes_multiples.sql
--   05_caso_avanzado_escalamiento.sql
--   06_caso_avanzado_penalizaciones.sql
--   07_caso_avanzado_bloqueo_recursos.sql
--   08_simulacion_20_incidentes.sql
--
-- NOTA IMPORTANTE:
--   06 queda preparado para validar una regla activa pendiente de la base:
--   penalización por demora. Hasta que esa regla esté implementada, ese script
--   debe fallar y sirve como guía.
-- =============================================================================
